export const LANG_SW_NAME = 'sw';

export const LANG_SW_TRANS = {
    'hello world': 'hello world',
    '@alert-alerts': 'Alerts',
    '@alert-temperature': 'Temperature Alerts',
    '@alert-disjunction': 'Disjunction Alerts',
    '@alert-out-of-zone': 'Zone exit Alerts',
    '@global-home': 'Home',
    '@global-back': 'Back',
    '@global-success': 'Success',
    '@global-warning': 'Warning',
    '@global-error': 'Error',
    '@global-add': 'Add',
    '@global-update': 'Update',
    '@global-edit': 'Edit',
    '@global-modify': 'Modify',
    '@global-remove': 'Remove',
    '@global-validate': 'Validate',
    '@global-delete': 'Delete',
    '@global-cancel': 'Cancel',
    '@global-duplicate': 'Duplicate',
    '@global-close': 'Close',
    '@global-apply': 'Apply',
    '@global-property': 'Property',
    '@global-properties': 'Properties',
    '@global-label': 'Label',
    '@global-external': 'External',
    '@global-models': 'Templates',
    '@global-model': 'Template',
    '@global-map': 'Map',
    '@global-details': 'Details',
    '@global-map-details': 'Map/Details',
    '@global-inventory': 'Inventory',
    '@global-graph': 'Graph',
    '@global-chart': 'Graphe',
    '@global-table': 'Table',
    '@global-board': 'Table',
    '@global-history': 'History',
    '@global-cabinets': 'Cabinets',
    '@global-cabinet': 'Cabinet',
    '@global-cabinet-type': 'Cabinet type',
    '@global-user': 'User',
    '@global-serial-number': 'Serial num',
    '@global-sensors': 'Sensors',
    '@global-sensor': 'Sensor',
    '@global-devices': 'Devices',
    '@global-device': 'Device',
    '@global-category': 'Category',
    '@global-connected-objects': 'Connected objects',
    '@global-connected-object': 'Connected object',
    '@global-meters': 'Mätare',
    '@global-meter': 'Mätare',
    '@global-organization': 'Organization',
    '@global-electrical-cabinet': 'Electrical cabinet',
    '@global-electrical-cabinets': 'Electrical cabinets',
    '@global-refresh': 'Uppdatera',
    '@global-name': 'Name',
    '@global-description': 'Description',
    '@global-area': 'Area',
    '@global-auto': 'Auto',
    '@global-automatic': 'Automatic',
    '@global-manual': 'Manual',
    '@global-nature': 'Nature',
    '@global-natures': 'Natures',
    '@global-login': 'Logga in',
    '@global-logout': 'Logga ut',
    '@global-welcom': 'Welcome to',
    '@global-username': 'Användarnamn',
    '@global-password': 'Lösenord',
    '@global-submit': 'Skicka',
    '@global-remain': 'Remain connected',
    '@global-dashboard': 'Dashboard',
    '@global-dashboards': 'Dashboards',
    '@global-dashboardslists': 'Dashboards lists',
    '@global-dashboardslist': 'Dashboards list',
    '@global-reports': 'Rapporter',
    '@global-trends': 'Trends',
    '@global-trend': 'Trend',
    '@global-points': 'Points',
    '@global-point': 'Point',
    '@global-folders': 'Folders',
    '@global-folder': 'Folder',
    '@global-trendsgroups': 'Trends groups',
    '@global-trendsgroup': 'Trends group',
    '@global-locations': 'Läge',
    '@global-location': 'Läge',
    '@global-sites': 'Sites',
    '@global-site': 'Site',
    '@global-breakers': 'Breakers',
    '@global-localization': 'Localization',
    '@global-identifier': 'Identifier',
    '@global-groups': 'Grupp',
    '@global-dataProviders': 'Data Providers',
    '@global-dataProvider': 'Data Provider',
    '@global-internal': 'Internal',
    '@global-consumption': 'Förbrukning',
    '@global-consumptions': 'Förbrukning',
    '@global-energy': 'Energy',
    '@global-alarms': 'Larm',
    '@global-categories': 'Categories',
    '@global-warnings': 'Warnings',
    '@global-remembers': 'Remembers',
    '@global-validations': 'Validations',
    '@global-profile': 'Profil',
    '@global-settings': 'Paremetrar',
    '@global-contact': 'Contact',
    '@global-help': 'Help',
    '@global-learn-more': 'Learn More',
    '@global-type': 'Type',
    '@global-message': 'Meddelande',
    '@global-alarm-date': 'Larmdatum',
    '@global-ack-date': 'Kvittera',
    '@global-drop-date': 'Normalt datum',
    '@global-measures': 'Measures',
    '@global-value': 'Value',
    '@global-state': 'Etat',
    '@global-date': 'Date',
    '@global-position': 'Position',
    '@global-positions': 'Positions',
    '@global-no': 'No',
    '@global-yes': 'Yes',
    '@global-connection': 'Connection',
    '@global-configuration': 'Configuration',
    '@global-commissioning': 'Commissioning',
    '@global-water': 'Water',
    '@global-electricity': 'Electricity',
    '@global-temperature': 'Temperature',
    '@global-disjunction': 'Disjunction',
    '@global-zone-exit': 'Out of area',
    '@global-total': 'Total',
    '@global-powered': 'Powered',
    '@global-not-powered': 'Not powered',
    '@global-battery-level': 'Battery level',
    '@global-unknow': 'Unknow',
    '@global-online': 'Online',
    '@global-offline': 'Offline',
    '@global-plug': 'Plug',
    '@global-unplug': 'Unplug',
    '@global-treeview': 'Tree view',
    '@global-filter': 'Filter',
    '@global-heatmap': 'Heatmap',
    '@global-general': 'General',
    '@global-parent': 'Parent',
    '@global-reference': 'Reference',
    '@global-source': 'Source',
    '@global-singleTrend': 'Single trend',
    '@global-multipleTrends': 'Multiple trends (multiple indexes)',
    '@global-manualEntry': 'Manual entry',
    '@global-multipleManualEntries': 'Manual entry (multiple indexes)',
    '@global-expression': 'Expression',
    '@global-conversion': 'Conversion',
    '@global-coefficient': 'Coefficient',
    '@global-offset': 'Offset',
    '@global-other': 'Other',
    '@global-unit': 'Unit',
    '@global-use': 'Use',
    '@global-tariff': 'Tariff',
    '@global-tariffs': 'Tariffs',
    '@global-report': 'Report',
    '@global-group': 'Group',
    '@global-color': 'Color',
    '@global-default': 'Default',
    '@global-tolerance': 'Tolerance',
    '@global-condition': 'Condition',
    '@global-severity': 'Severity',
    '@global-thresholds': 'Thresholds',
    '@global-threshold': 'Threshold',
    '@global-plannings': 'Plannings',
    '@global-planning': 'Planning',
    '@global-customProperties': 'Custom properties',
    '@global-customProperty': 'Custom property',
    '@global-server': 'Server',
    '@global-size': 'Size',
    '@global-database': 'Database',
    '@global-udds': 'Degree Days',
    '@global-none-m': 'Nonthing',
    '@global-none-f': 'Nonthing',
    '@global-calculated': 'Calculated',
    '@global-base': 'Base',
    '@global-method': 'Method',
    '@global-calendar': 'Calendar',
    '@global-calendars': 'Calendars',
    '@global-mediane': 'Mediane',
    '@global-average': 'Average',
    '@global-simple': 'Simple',
    '@global-pro': 'Pro',
    '@global-search': 'Search',
    '@global-elements': 'Elements',
    '@global-personalized': 'Personalized',
    '@global-display': 'Display',
    '@global-display_verb': 'Display',
    '@global-activate': 'Active',
    '@global-definition': 'Definition',
    '@global-refreshTime': 'Refresh time',
    '@global-refreshPeriod': 'Refresh period',
    '@global-mode': 'Mode',
    '@global-tables': 'Tables',
    '@global-localTime': 'Local time',
    '@global-utc': 'UTC',
    '@global-fileTime': 'File time',
    '@global-fileTimeDesc': '100 ns intervals since 1601/1/1',
    '@global-optional': 'Optional',
    '@global-connections': 'Connections',
    '@global-configure': 'Configure',
    '@global-integrated': 'Integrated',
    '@global-enable': 'Enable',
    '@global-disable': 'Disable',
    '@global-disabled': 'Disabled',
    '@global-customized': 'Customized',
    '@global-none': 'None',
    '@global-data:': 'Data',
    '@global-onChanges': 'On change',
    '@global-title': 'Title',
    '@global-defaultPeriod': 'Default period',
    '@global-offsetUnit': '',
    '@global-secondOffset': 'Second offset',
    '@global-duration': 'Duration',
    '@global-durationUnit': '',
    '@global-background': 'Background',
    '@global-foreground': 'Foreground',
    '@global-image': 'Image',
    '@global-opacity': 'Opacity',
    '@global-browse': 'Browse',
    '@global-period': 'Period',
    '@global-picture': 'Image',
    '@global-functions': 'Functions',
    '@global-columns': 'Columns',
    '@global-rows': 'Rows',
    '@global-actions': 'Actions',
    '@global-action': 'Action',
    '@global-width': 'Width',
    '@global-height': 'Height',
    '@global-displayValue': 'Display value',
    '@global-format': 'Format',
    '@global-minimum': 'Minimum',
    '@global-maximum': 'Maximum',
    '@global-level': 'Level',
    '@global-legend': 'Legend',
    '@global-perUnitOfArea': 'Per unit of area',
    '@global-url': 'URL',
    '@global-fontSize': 'Font size',
    '@global-beginning': 'Beginning',
    '@global-primary': 'Primary energy',
    '@global-carbon': 'Carbon',
    '@global-cost': 'Cost',
    '@global-unitPrice': 'Unit price',
    '@global-textColor': 'Text color',
    '@global-backgroundImage': 'Background image',
    '@global-hardwareAddress': 'Hardware address',
    '@global-options': 'Options',
    '@global-status': 'Status',
    '@global-instance': 'Instance',
    '@global-ipAddress': 'Ip address',
    '@global-port': 'Port',
    '@global-portUdp': 'UDP Port',
    '@global-standardPort': 'Standard port',
    '@global-range': 'Range',
    '@global-address': 'Address',
    '@global-addresses': 'Addresses',
    '@global-from': 'From',
    '@global-to': 'To',
    '@global-global': 'Global',
    '@global-local': 'Local',
    '@global-remote': 'Remote',
    '@global-broadcast': 'Broadcast',
    '@global-numberOfRetries': 'Number of retries',
    '@global-requestTimeout': 'Request timeout',
    '@global-import': 'Import',
    '@global-objCount': 'Object count',
    '@global-vendorId': 'Vendor Id',
    '@global-addressLength': 'Address length',
    '@global-pollingPeriod': 'Polling period',
    '@global-clockSyncPeriod': 'Clock sync. period',
    '@global-explorationDuration': 'Exploration duration',
    '@global-unlimited': 'Unlimited',
    '@global-maxTransactionsPerDevice': 'Max transaction per device',
    '@global-multiple' : 'Multiple selection',
    '@global-play': 'Play',
    '@global-energyEfficiencyRating': 'Energy efficiency rating',
    '@global-indicator' : 'Indicator',
    '@global-template': 'Template',
    '@global-templates': 'Templates',
    '@global-startDate': 'Start date',
    '@global-endDate': 'End date',
    '@global-defaultElement': 'Default element',
    '@global-orientation': 'Orientation',
    '@global-portrait': 'Portrait',
    '@global-landscape': 'Landscape',
    '@global-borderColor': 'Border color',
    '@global-authorization': 'Authorization',
    '@global-leftImage': 'Left image',
    '@global-rightImage': 'Right image',
    '@global-logo': 'Logo',
    '@global-leftLogo': 'Left logo',
    '@global-rightLogo': 'Right logo',
    '@global-content': 'Content',
    '@global-newLine': 'New line',
    '@global-newPage': 'New page',
    '@global-sampling': 'Sampling',
    '@global-element': 'Element',
    '@global-axis': 'Axis',
    '@global-text': 'Text',
    '@global-pie': 'Pie',
    '@global-formatting': 'Formatting',
    '@global-infos': 'Infos',
    '@global-field': 'Field',
    '@global-fields': 'Fields',
    '@global-variable': 'Variable',
    '@global-variables': 'Variables',
    '@global-attributes': 'Attributes',
    '@global-sum': 'Sum',
    '@global-parameters': 'Parameters',
    '@global-dataToDisplay': 'Data to display',
    '@global-data': 'Data',
    '@global-showValue': 'Show value',
    '@global-showValues': 'Show values',
    '@global-legends': 'Legends',
    '@global-valueOfCurrentElement': 'Value of current element',
    '@global-greenHouseGasEmission': 'Greenhouse Gas Emission',
    '@global-exportInProgress': 'Export in progress',
    '@global-export': 'Export',
    '@global-exportHistory': 'Export history',
    '@global-exportGrid': 'Export grid',
    '@global-exportConfiguration': 'Export configuration',
    '@global-separator': 'Separator',
    '@global-displayInfo': 'Display info',
    '@global-numberOfValues': 'Number of values',
    '@global-lastValue': 'Last value',
    '@global-performance': 'Performance',
    '@global-network': 'Network',
    '@global-trace': 'Trace',
    '@global-connectionType': 'Connection type',
    '@global-serialPort': 'Serial port',
    '@global-baudRate': 'Baud rate',
    '@global-timeout': 'Timeout',
    '@global-errors': 'Errors',
    '@global-statistics': 'Statistics',
    '@global-registers': 'Registers',
    '@global-connecting': 'Connecting',
    '@global-connected': 'Connected',
    '@global-disconnected': 'Disconnected',
    '@global-lastError': 'Last error',
    '@global-numberOfTries': 'Number of tries',
    '@global-cycleDuration': 'Cycle duration',
    '@global-lowByteFirst': 'Low byte first',
    '@global-lowWordFirst': 'Low word first',
    '@global-count': 'Count',
    '@global-copiedToClipboard': 'Copied to clipboard',
    '@global-copyUrl': 'Copy Url',
    '@global-distribution': 'Distribution',
    '@global-files': 'Files',
    '@global-file': 'File',
    '@global-path': 'Path',
    '@global-drive': 'Drive',
    '@global-and': 'and',
    '@global-active': 'Active',
    '@global-passive': 'Passive',
    '@global-preview': 'Preview',
    '@global-clearCache': 'Clear cache',
    '@global-list': 'List',
    '@global-editionMode': 'Edition mode',
    '@global-fullscreen': 'Fullscreen',
    '@global-start_verb': 'Start',
    '@global-noMenu': 'No menu',
    '@global-left': 'Left',
    '@global-right': 'Right',
    '@global-min': 'Min',
    '@global-max': 'Max',
    '@global-baseline': 'Baseline',
    '@global-displayIndex': 'Display index',
    '@global-showIndicator': 'Show indicator',
    '@global-fontColor': 'Font color',
    '@global-tiles': 'Tiles',
    '@global-deleteFromList': 'Delete from list',
    '@global-nullAsZero': 'Replace a missing value by zero',
    '@global-dynamicColors': 'Dynamic colors',
    '@global-defaultFontColor': 'Default font color',
    '@global-defaultTextColor': 'Default text color',
    '@global-defaultBackground': 'Default background',
    '@global-defaultTitleColor': 'Default title color',
    '@global-titleColor': 'Title color',
    '@global-consump./product.': 'Consump./Product.',
    '@global-production': 'Production',
    '@global-instances': 'Instances',
    '@global-comments': 'Comments',
    '@global-comment': 'Comment',
    '@global-miscellaneous': 'Miscellaneous',
    '@global-misc.': 'Misc.',
    '@global-minDuration': 'Min. Duration',
    '@global-dates': 'Dates',
    '@global-affectation-date': 'Affectation date',
    '@global-last-communication-date': 'Last communication date',
    '@global-startdate': 'Anfangsdatum',
    '@global-enddate': 'Enddatum',
    '@global-decennary': 'Decennary',
    '@global-year': 'Jahre',
    '@global-month': 'Monat',
    '@global-week': 'Woche',
    '@global-day': 'Tag',
    '@global-hour': 'Stunde',
    '@global-minute': 'Minuten',
    '@global-seconde': 'Sekunden',
    '@global-per-year': 'Per Years',
    '@global-per-month': 'Per Month',
    '@global-per-week': 'Per Week',
    '@global-per-day': 'Per Day',
    '@global-per-hour': 'Per Hour',
    '@global-per-minute': 'Per Minute',
    '@global-per-seconde': 'Per Second',
    '@global-daily': 'Daily',
    '@global-monthly': 'Monthly',
    '@global-yearly': 'Yearly',
    '@global-currentHour': 'Current hour',
    '@global-currentDay': 'Current day',
    '@global-currentWeek': 'Current week',
    '@global-currentMonth': 'Current month',
    '@global-currentYear': 'Current year',
    '@global-hours': 'Hours',
    '@global-days': 'Days',
    '@global-weeks': 'Weeks',
    '@global-months': 'Months',
    '@global-years': 'Years',
    '@global-seconds': 'Seconds',
    '@global-currentDate': 'Current date',
    '@global-nameOfMonth': 'Name of month',
    '@global-weekNumber': 'Week number',
    '@global-january': 'January',
    '@global-february': 'February',
    '@global-march': 'March',
    '@global-april': 'April',
    '@global-may': 'May',
    '@global-june': 'June',
    '@global-july': 'July',
    '@global-august': 'August',
    '@global-september': 'September',
    '@global-october': 'October',
    '@global-november': 'November',
    '@global-december': 'December',
    '@global-january_abrv': 'Jan',
    '@global-february_abrv': 'Feb',
    '@global-march_abrv': 'Mar',
    '@global-april_abrv': 'Apr',
    '@global-may_abrv': 'May',
    '@global-june_abrv': 'Jun',
    '@global-july_abrv': 'Jul',
    '@global-august_abrv': 'Aug',
    '@global-september_abrv': 'Sep',
    '@global-october_abrv': 'Oct',
    '@global-november_abrv': 'Nov',
    '@global-december_abrv': 'Dec',
    '@global-monday': 'Monday',
    '@global-tuesday': 'Tuesday',
    '@global-wednesday': 'Wednesday',
    '@global-thursday': 'Thursday',
    '@global-friday': 'Friday',
    '@global-saturday': 'Saturday',
    '@global-sunday': 'Sunday',
    '@global-monday_abrv': 'Mon',
    '@global-tuesday_abrv': 'Tue',
    '@global-wednesday_abrv': 'Wed',
    '@global-thursday_abrv': 'Thu',
    '@global-friday_abrv': 'Fri',
    '@global-saturday_abrv': 'Sat',
    '@global-sunday_abrv': 'Sun',
    '@global-previousDay': 'Previous day',
    '@global-previousWeek': 'Previous week',
    '@global-previousMonth': 'Previous month',
    '@global-previousYear': 'Previous year',
    '@global-alarm': 'Alarm',
    '@global-lessThan': 'Less than',
    '@global-greaterThan': 'Greater than',
    '@global-referenceYear': 'Reference Year',
    '@global-manualEntries': 'Manual entries',
    '@global-addValue': 'Add value',
    '@global-deleteValue': 'Delete value',
    '@global-accumulation': 'Accumulation',
    '@global-difference': 'Difference',
    '@global-price': 'Price',
    '@global-newReading': 'New reading',
    '@global-plans': 'Plans',
    '@global-plan': 'Plan',
    '@global-saveAndExit': 'Save and exit',
    '@global-exitWithoutSave': 'Exit without save',
    '@global-borderSize': 'Border size',
    '@global-edition': 'Edition',
    '@global-save': 'Save',
    '@global-exit': 'Exit',
    '@global-phase': 'Phase',
    '@global-input': 'Input',
    '@global-output': 'Output',
    '@global-ups': 'Ups',
    '@global-rack': 'Rack',
    '@global-crac': 'Crac',
    '@global-apparentPower': 'Apparent power',
    '@global-activePower': 'Active power',
    '@global-reactivePower': 'Reactive power',
    '@global-powerFactor': 'Power factor',
    '@global-current': 'Current',
    '@global-voltage': 'Voltage',
    '@global-batteryCharge': 'Battery Charge',
    '@global-frequency': 'Frequency',
    '@global-reactiveEnergy': 'Reactive Energy',
    '@global-temperatureIn': 'Temperature in',
    '@global-temperatureOut': 'Temperature out',
    '@global-load': 'Load',
    '@global-outletState': 'OutletState',
    '@global-criterion': 'Criterion',
    '@global-criteria': 'Criteria',
    '@global-attribute': 'Attribute',
    '@global-maxCount': 'Max count',
    '@global-sort': 'Sort',
    '@global-sorting': 'Sorting',
    '@global-sortDirection': 'Sort direction',
    '@global-ascending': 'Ascending',
    '@global-descending': 'Descending',
    '@global-function': 'Function',
    '@global-convertion': 'Convertion',
    '@global-ratio': 'Ratio',
    '@global-finalEnergy': 'Final energy',
    '@global-primaryEnergy': 'Primary energy',
    '@global-cO2': 'CO²',
    '@global-indexStart': 'Start index',
    '@global-indexStop': 'Stop index',
    '@global-perAreaUnit': 'Per area unit',
    '@global-perDegreeDays': 'Per degree days',
    '@global-first': 'First',
    '@global-last': 'Last',
    '@global-rename': 'Rename',
    '@global-research': 'Research',
    '@global-showCrosshair': 'Show crosshair',
    '@global-trendPeriod': 'Trend period',
    '@global-communityRead': 'Community read',
    '@global-communityWrite': 'Community write',
    '@global-hostname': 'Hostname',
    '@global-version': 'Version',
    '@global-supportMultipleRequests': 'Support multiple requests',
    '@global-explore': 'Explore',
    '@global-pdus': 'Pdus',
    '@global-upss': 'Ups',
    '@global-cracs': 'Cracs',
    '@global-racks': 'Racks',
    '@global-compartments': 'Compartments',
    '@global-maxAmp': 'Max amp.',
    '@global-power': 'Power',
    '@global-amp': 'Amperage',
    '@global-tempIn': 'Temp. in',
    '@global-tempOut': 'Temp. out',
    '@global-maxCurrent': 'Max current',
    '@global-appPower': 'Apparent power',
    '@global-actPower': 'Active power',
    '@global-reactPower': 'React power',
    '@global-temp': 'Temp.',
    '@global-maxVa': 'Max VA',
    '@global-battery': 'Battery',
    '@global-inputVoltage': 'Input voltage',
    '@global-pf': 'PF',
    '@global-displayRealTimeState': 'Display real time state',
    '@global-fixed': 'Fixed',
    '@global-activity': 'Activity',
    '@global-heating': 'Heating',
    '@global-cooling': 'Cooling',
    '@global-heatingReference': 'Heating Reference',
    '@global-coolingReference': 'Cooling Reference',
    '@global-region': 'Region',
    '@global-building': 'Building',
    '@global-datacenter': 'Datacenter',
    '@global-corridor': 'Corridor',
    '@global-row': 'Row',
    '@global-latitude': 'Latitude',
    '@global-longitude': 'Longitude',
    '@global-axes': 'Axes',
    '@global-print': 'Print',
    '@global-print_verb': 'Print',
    '@global-cumul': 'Cumul',
    '@global-normalized': 'Normalized',
    '@global-byDegreeDays': 'By degree days',
    '@global-showPreviousYear': 'Show previous year',
    '@global-cumulated': 'Cumulated',
    '@global-power/flowRate': 'Power/Flow rate',
    '@global-informations': 'Informations',
    '@global-clientOperatingSystem': 'Client operating system',
    '@global-environmentCode': 'Environment code',
    '@global-licenseState': 'License state',
    '@global-organizations': 'Organizations',
    '@global-remoteSyncEnabled': 'Remote sync. enabled',
    '@global-remoteSyncServerEnabled': 'Remote sync. server enabled',
    '@global-license': 'License',
    '@global-sentMessage': 'Sent message',
    '@global-sendMessage': 'Send message',
    '@global-media': 'Media',
    '@global-recipient': 'Recipient',
    '@global-recipients': 'Recipients',
    '@global-normal': 'Normal',
    '@global-acked': 'Acked',
    '@global-subject': 'Subject',
    '@global-groupMessages': 'Group messages',
    '@global-notactivated': 'Not activated',
    '@global-every': 'Every',
    '@global-created': 'Created',
    '@global-updated': 'Updated',
    '@global-deleted': 'Deleted',
    '@default-data': 'Default data',
    '@default-period': 'Default period',
    '@default-element': 'Default element',
    '@default-elements': 'Default elements',
    '@default-parameters': 'Default parameters',
    '@default-list': 'Default List',
    '@default-duration': 'Default duration',
    '@period-refresh': 'Refresh period',
    '@period-equivalent': 'Equivalent period',
    '@period-equivalentToCurrent': 'Equivalent period to the current period',
    '@period-waitEnd': 'Wait end of period',
    '@start-none': 'None',
    '@offset-none': 'None',
    '@element-none': 'None',
    '@element-add': 'Add element',
    '@elements-import': 'Import elements',
    '@tariff-simple': 'Simple tariff',
    '@tariff-multipleStats': 'Multi-stats tariff',
    '@tariff-adjustment': 'Tariff adjustment',
    '@meter-id': 'Id',
    '@meter-name': 'Namn',
    '@meter-locationId': 'Läge Id',
    '@meter-consumption': 'Förbrukning',
    '@meter-nature': 'Slags',
    '@meter-unit': 'Enhet',
    '@meter-location': 'Läge',
    '@meter-area': 'Område',
    '@meter-expression': 'Uttryck',
    '@meter-organization': 'Organisationer',
    '@meter-indexlastvalue' : 'Index Sista värde',
    '@meter-indexlastdate' : 'Index Sista datum',
    '@meter-nometerfound': 'No meter found',
    '@meter-principal': 'Principal meter',
    '@meter-accumulation': 'Accumulation',
    '@meter-noInterpolation': 'No interpolation',
    '@meter-scalingCoef': 'Scaling coef.',
    '@meter-distributionCoef': 'Distribution coef.',
    '@meter-rolloverLimit': 'Rollover limit',
    '@meter-maxDaily': 'Max. daily consumption (0 = auto)',
    '@meter-onlyUsed': 'Only used meters',
    '@meter-create' : 'Create meter',
    '@meter-list' : 'Meters list',
    '@meter-addSub': 'Add sub meter',
    '@meter-none': 'No meter',
    '@meter-shift': 'Shift meter',
    '@meter-newShift': 'New shift',
    '@meters-(automatic)': 'Meters (automatic)',
    '@meters-(manual)': 'Meters (manual)',
    '@meters-(other)': 'Meters (other)',
    '@meter-noManualEntryAvailable': 'No meter in manual entry mode available',
    '@location-type': 'Location type',
    '@location-includeSub': 'Include sub-locations',
    '@location-addSub': 'Add sub location',
    '@location-none': 'No location',
    '@location-moveTo': 'Move to location',
    '@location-addMeterTo': 'Add meter to location',
    '@location-deleteFrom': 'Delete from location',
    '@location-by': 'By location',
    '@group-includeSub': 'Include sub-groups',
    '@group-addSub': 'Add sub group',
    '@group-none': 'No group',
    '@group-addTo': 'Add to group',
    '@group-addMeterTo': 'Add meter to group',
    '@group-deleteFrom': 'Delete from group',
    '@dashboard-columnsNumber' : 'Column count',
    '@dashboard-rowsNumber' : 'Row count',
    '@dashboard-tilesStyle' : 'Tiles style',
    '@dashboard-addTile' : 'Add a tile',
    '@dashboard-value' : 'Value',
    '@dashboard-chart' : 'Bar / Curve chart',
    '@dashboard-pie' : 'Pie chart',
    '@dashboard-gauge' : 'Gauge',
    '@dashboard-indicator' : 'Energy efficiency rating',
    '@dashboard-image' : 'Image',
    '@dashboard-autoUnit' : 'Automatic unit',
    '@dashboard-textColor' : 'Text color',
    '@dashboard-dynamicColors' : 'Dynamic background colors',
    '@dashboard-actionType' : 'Action type',
    '@dashboard-bySubLocationGroup' : 'By sub-location/group',
    '@dashboard-byNature' : 'By nature',
    '@dashboard-showPercentage' : 'Show percentage',
    '@dashboard-showValue' : 'Show value',
    '@dashboard-deleteFromList': 'Delete from list',
    '@dashboard-showTrend': 'Show a trend',
    '@dashboard-showTrendsGroup': 'Show a trends group',
    '@dashboard-openWebPage': 'Open a web page',
    '@dashboard-showDashboard': 'Show a dashboard',
    '@dashboard-showConsumptionHistory': 'Show a consumption history',
    '@dashboard-meterListDesc': '',
    '@dashboard-lists': 'Dashboards lists',
    '@dashboard-list': 'Dashboards list',
    '@dashboard-all': 'All dashboards',
    '@dashboard-options': 'Dashboard options',
    '@dashboard-tileDefaultColor': 'Change tile default color (if value is unavailable)',
    '@group-basedOnSubGroups': 'based on sub-groups',
    '@group-basedOnMeters': 'based on meters',
    '@object-type': 'Object type',
    '@alarm-only-active': 'Only active alarms',
    '@alarm-only-active-unacked': 'Only active and non acknowledged alarms',
    '@alarm-history': 'Alarm history',
    '@alarm-instances': 'Alarm instances',
    '@alarm-configuration': 'Alarms configuration',
    '@alarms-definitions': 'Alarms definitions',
    '@alarm-ack': 'Ack alarm',
    '@alarm-active': 'Alarm active',
    '@alarm-deactive': 'Alarm inactive',
    '@alarm-ackActive': 'Alarm ack active',
    '@alarm-ackDeactive': 'Alarm ack inactive',
    '@alarm-none': 'None',
    '@alarm-presents': 'Present alarms',
    '@alarm-defaultMessage': 'Default alarm message',
    '@alarm-personalizedMessage': 'Personalized alarm message',
    '@alarm-state': 'Alarm state',
    '@alarm-date': 'Alarm date',
    '@alarm-message': 'Alarm message',
    '@alarm-identifier': 'Alarm identifier',
    '@alarm-category': 'Alarm category',
    '@alarm-nameOfAssocatedElement': 'Name of associated element (point, trend, ...)',
    '@alarm-valueOfAssocatedElement': 'Value of associated element',
    '@alarm-stateOfAssocatedPlanning': 'State of the planning associated with the alarm',
    '@alarm-location': 'Alarm location',
    '@alarm-describtionOfLocation': 'Alarm location description',
    '@alarm-locationOfLocation': 'Parent location of the alarm location',
    '@alarm-labelOfpropertyOfAssocatedDevice': 'Label of the property of the associated device',
    '@alarm-lebalOfAssocatedMeasure': 'Label of the associated measure',
    '@site-history': 'Site history',
    '@site-add': 'Add a site',
    '@site-edit-zone': 'Edit site area',
    '@connection-add': 'Add connection',
    '@connection-edit': 'Edit connection',
    '@connection-delete': 'Delete connection',
    '@connection-refresh': 'Refresh connection',
    '@connection-update': 'Update connection',
    '@connection-tcp': 'Tcp Connection',
    '@connection-test': 'Connection test',
    '@connection-serial': 'Serial Connection',
    '@connection-success': 'Connection Succeeded',
    '@connection-failed': 'Connection Failed',
    '@consumption-degrees_day' : 'Degrees-Days',
    '@consumption-electricity-of' : 'Electricity consumption',
    '@consumption-water-of' : 'Water consumption',
    '@consumptions-normalized': 'Normalized consumptions',
    '@consumption-reference': 'Reference consumption',
    '@consumption-baseline': 'Baseline consumption',
    '@source-none': 'None',
    '@alarm-definition': 'Alarm definition',
    '@device-type': 'Device type',
    '@device-data-provider': 'Data Provider',
    '@device-reference': 'Reference',
    '@device-geolocation': 'Geolocation',
    '@device-all': 'All devices',
    '@device-add': 'Add device',
    '@device-edit': 'Edit device',
    '@device-update': 'Update device',
    '@device-delete': 'Delete device',
    '@device-explore': 'Explore device',
    '@device-instance': 'Device instance',
    '@device-statusPeriod': 'Device status period',
    '@devices-import': 'Devices import',
    '@devices-display': 'Display devices',
    '@cabinet-add': 'Add a cabinet',
    '@cabinet-validate-position': 'Validate cabinet\'s position',
    '@cabinet-edit-position': 'Edit cabinet\'s position',
    '@cabinet-delete-position': 'Delete cabinet\'s position',
    '@cabinets-by-type': 'Sort by type of cabinet',
    '@trend-none': 'None',
    '@trend-all': 'All trends',
    '@trend-udds': 'Degree days trend',
    '@trend-outdoorTemperature': 'Outdoor temperature trend',
    '@trend-create': 'Create trend',
    '@trend-fromPoint': 'Trend from a point',
    '@trend-conversion': 'Trend conversion',
    '@trends-create': 'Create trends',
    '@measure-temperature': 'Temperature',
    '@measure-battery': 'Battery',
    '@unit-conversion': 'Unit conversion',
    '@nature-electricity': 'Electricity',
    '@nature-water': 'Water',
    '@nature-sourceEnergyCoef': 'Source Energy coef.',
    '@nature-CO2PerUnit': 'Kg CO2 per unit',
    '@nature-by': 'By nature',
    '@use-heating': 'Heating',
    '@use-cooling': 'Cooling',
    '@point-all': 'All points',
    '@point-readValue': 'Read value',
    '@point-readValues': 'Read values',
    '@points-show': 'Show points',
    '@report-all': 'All reports',
    '@report-none': 'None',
    '@plan-all': 'All plans',
    '@plan-properties': 'Plan properties',
    '@udds-none': 'None',
    '@udds-heating': 'Degree days heating',
    '@udds-cooling': 'Degree days cooling',
    '@sampling-none': 'None',
    '@method-none': 'No method',
    '@temperature-mediane': 'Use the mediane temperature',
    '@temperature-average': 'Use the average temperature',
    '@temperature-input': 'Input temperature',
    '@temperature-output': 'Output temperature',
    '@temperature-indoor': 'Indoor temperature',
    '@temperature-outdoor': 'Outdoor temperature',
    '@password-change': 'Changement de mot de passe',
    '@password-current': 'Current password',
    '@password-new': 'New password',
    '@password-confirmation': 'Password confirmation ',
    '@password-cannot-change': 'You cannot change password',
    '@configuration-save': 'Save configuration',
    '@database-infos': 'Database infos',
    '@database-connectionString': 'Connection string',
    '@database-columns': 'Columns',
    '@database-columnsDate': 'Date columns',
    '@database-columnsValue': 'Value columns',
    '@database-columnsReference': 'Reference columns',
    '@database-mapping': 'Mapping',
    '@database-sqlRequests': 'SQL requests',
    '@database-mappingListRef': 'List of name / references',
    '@database-mappingRefConvert': 'Converts a reference ({0}) to a reference used in the table of values',
    '@database-name': 'Database name',
    '@database-dbfFile': '.Dbf File',
    '@server-name': 'Server name',
    '@server-version': 'Server version',
    '@server-add': 'Add server',
    '@server-memoryUsage(MB)': 'Server memory usage (MB)',
    '@zoom-reset': 'Reset zoom',
    '@xml-edit': 'Edit XML',
    '@xml-editor': 'XML Editor',
    '@entry': 'Entry',
    '@entries': 'Entries',
    '@entry-add': 'Add entry',
    '@date-chooseA': 'Choose a date',
    '@authentication-basic': 'Basic authentication',
    '@bacnet-configuration': 'BACnet Configuration',
    '@bacnet-exploration': 'BACnet Exploration',
    '@bacnet-networkNumber': 'BACnet Network number',
    '@bacnet-impossibleImportTrendsAndPoints': 'Impossible to import points and trends simultaneously',
    '@modbus-tcpHeader': 'Modbus TCP Header',
    '@modbus-connectionConfiguration': 'Modbus connection configuration',
    '@modbus-deviceConfiguration': 'Modbus device configuration',
    '@modbus-type_B': 'Binary',
    '@modbus-type_Bi': 'Binary (input)',
    '@modbus-type_D': 'Real 64bits',
    '@modbus-type_Di': 'Real 64bits (input)',
    '@modbus-type_F': 'Real 32bits',
    '@modbus-type_Fi': 'Real 32bits (input)',
    '@modbus-type_K': 'Integer 48bits',
    '@modbus-type_Ki': 'Integer 48bits (input)',
    '@modbus-type_Kis': 'Signed integer 48bits (input)',
    '@modbus-type_Ks': 'Signed integer 48bits',
    '@modbus-type_L': 'Integer 32bits',
    '@modbus-type_Li': 'Integer 32bits (input)',
    '@modbus-type_Lis': 'Signed integer 32bits (input)',
    '@modbus-type_LL': 'Integer 64bits',
    '@modbus-type_LLi': 'Integer 64bits (input)',
    '@modbus-type_LLis': 'Signed integer 64bits (input)',
    '@modbus-type_LLs': 'Signed integer 64bits',
    '@modbus-type_Ls': 'Signed integer 32bits',
    '@modbus-type_T': 'Text',
    '@modbus-type_W': 'Integer 16bits',
    '@modbus-type_Wi': 'Integer 16bits (input)',
    '@modbus-type_Wis': 'Signed integer 16bits (input)',
    '@modbus-type_Ws': 'Signed integer 16bits',
    '@multitech-deletionAuthorization': 'Device deletion authorized',
    '@multitech-messages': 'Messages',
    '@multitech-lastmessage': 'Last date',
    '@multitech-nodeaddr': 'Node address',
    '@multitech-deveui': 'DevEui',
    '@multitech-appeui': 'AppEui',
    '@multitech-appkey': 'AppKey',
    '@multitech-rssi': 'Rssi',
    '@multitech-snr': 'Snr',
    '@multitech-datarate': 'Data rate',
    '@multitech-class': 'Class',
    '@multitech-addr': 'Adr',
    '@multitech-otaa': 'OTAA',
    '@multitech-abp': 'ABP',
    '@multitech-periodicRetrievalOfMessages': 'Periodic retrieval of the messages',
    '@multitech-pollingPeriod': 'Polling period (seconds)',
    '@multitech-nodeRedConnectionEnabled': 'Node-RED connection activated',
    '@multitech-messageOnConnection': 'Retrieve messages on connection',
    '@multitech-statusCheck': 'Gateway status check',
    '@file-types': 'File types',
    '@file-import': 'File import',
    '@file-paths': 'File paths',
    '@file-hasHeader': 'The file has an header',
    '@file-reading': 'File reading',
    '@file-chooseRemote': 'Choose a remote file',
    '@file-chooseLocal': 'Choose a local file',
    '@file-choose': 'Choose a file',
    '@file-name': 'File name',
    '@network-number': 'Network number',
    '@network-explore': 'Explore network',
    '@network-interfaces': 'Network interfaces',
    '@consumption-history' : 'Consumption history',
    '@consumption-table': 'Consumption table',
    '@consumption-chart': 'Consumption chart',
    '@consumption-graph': 'Consumption chart',
    '@consumption-conversion': 'Consumption conversion',
    '@consumption-useReference': 'Use reference consumption',
    '@tile-Titles': 'Tile titles',
    '@chart-cumul': 'Cumulated graph',
    '@error-name-field-required': 'The \'Name\' is required',
    '@error-this-field-required': 'This field is required',
    '@error-impossibleImportTrendsAndPoints': 'Impossible to import trends and points simultaneously',
    '@sentence-no-data': 'No data found',
    '@sentence-are-you-sure': 'Are you sure ?',
    '@sentence-server-connect': 'Unable to connect to the server',
    '@sentence-user-or-pass': 'Username or password is incorrect',
    '@sentence-remove-failed': 'The removal failed',
    '@sentence-impossible-uo': 'Unable to remove the UO as long as there are cabinets left',
    '@sentence-impossible-site': 'Unable to remove the site as long as there are cabinets left',
    '@sentence-unknown-url': 'Unknown URL',
    '@sentence-someValuesAreNotValidated.': 'Some values are not validated.',
    '@sentence-someValuesAreNotValidated.AreYouSureToContinue?': 'Some values are not validated. Are you sure to continue ?',
    '@info-warningIE': 'The application is optimized for modern browsers. On Internet Explorer the display may be degraded',
    '@threshold-none': 'None',
    '@type-none': 'None',
    '@attribute-none': 'None',
    '@filter-none': 'None',
    '@filter-EqOperator': 'Is equal to',
    '@filter-NotEqOperator': 'Is not equal to',
    '@filter-IsNullOperator': 'Is null',
    '@filter-IsNotNullOperator': 'Is not null',
    '@filter-IsEmptyOperator': 'Is empty',
    '@filter-IsNotEmptyOperator': 'Is not empty',
    '@filter-StartsWithOperator': 'Starts with',
    '@filter-ContainsOperator': 'Contains',
    '@filter-NotContainsOperator': 'Does not contain',
    '@filter-EndsWithOperator': 'Ends with',
    '@filter-GteOperator': 'Is greater than or equal to',
    '@filter-GtOperator': 'Is greater than',
    '@filter-LteOperator': 'Is less than or equal to',
    '@filter-LtOperator': 'Is less than',
    '@filter-IsTrue': 'is true',
    '@filter-IsFalse': 'is false',
    '@filter-BooleanAll': '(All)',
    '@filter-AfterOrEqualOperator': 'Is after or equal to',
    '@filter-AfterOperator': 'Is after',
    '@filter-BeforeOperator': 'Is before',
    '@filter-BeforeOrEqualOperator': 'Is before or equal to',
    '@filter-FilterButton': 'Filter',
    '@filter-ClearButton': 'Clear',
    '@filter-AndLogic': 'And',
    '@filter-OrLogic': 'Or',
};
