export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
    'hello world': 'Bonjour tout le monde',
    '@alert-alerts': 'Alertes',
    '@alert-temperature': 'Alertes Température',
    '@alert-disjunction': 'Alertes Disjonction',
    '@alert-out-of-zone': 'Alertes Sortie de Zone',
    '@global-home': 'Accueil',
    '@global-back': 'Retour',
    '@global-success': 'Succès',
    '@global-warning': 'Attention',
    '@global-error': 'Erreur',
    '@global-add': 'Ajouter',
    '@global-update': 'Mettre à jour',
    '@global-edit': 'Editer',
    '@global-modify': 'Modifier',
    '@global-remove': 'Supprimer',
    '@global-validate': 'Valider',
    '@global-delete': 'Supprimer',
    '@global-cancel': 'Annuler',
    '@global-duplicate': 'Dupliquer',
    '@global-close': 'Fermer',
    '@global-apply': 'Appliquer',
    '@global-property': 'Propriété',
    '@global-properties': 'Propriétés',
    '@global-label': 'Libellé',
    '@global-external': 'Externe',
    '@global-models': 'Modèles',
    '@global-model': 'Modèle',
    '@global-map': 'Carte',
    '@global-details': 'Détails',
    '@global-map-details': 'Carte/Détails',
    '@global-inventory': 'Inventaire',
    '@global-graph': 'Graphe',
    '@global-chart': 'Graphe',
    '@global-board': 'Tableau',
    '@global-table': 'Tableau',
    '@global-history': 'Historique',
    '@global-cabinets': 'Armoires',
    '@global-cabinet': 'Armoire',
    '@global-cabinet-type': 'Type d\'armoire',
    '@global-user': 'Utilisateur',
    '@global-serial-number': 'No de série',
    '@global-sensors': 'Capteurs',
    '@global-sensor': 'Capteur',
    '@global-devices': 'Appareils',
    '@global-device': 'Appareil',
    '@global-category': 'Catégorie',
    '@global-connected-objects': 'Objets connectés',
    '@global-connected-object': 'Objet connecté',
    '@global-meters': 'Compteurs',
    '@global-meter': 'Compteur',
    '@global-organization': 'Organisation',
    '@global-electrical-cabinet': 'Armoire électrique',
    '@global-electrical-cabinets': 'Armoires électriques',
    '@global-refresh': 'Rafraîchir',
    '@global-name': 'Nom',
    '@global-description': 'Description',
    '@global-area': 'Surface',
    '@global-auto': 'Auto',
    '@global-automatic': 'Automatique',
    '@global-manual': 'Manuel',
    '@global-nature': 'Nature',
    '@global-natures': 'Natures',
    '@global-login': 'Connexion',
    '@global-logout': 'Déconnexion',
    '@global-welcom': 'Bienvenue dans',
    '@global-username': 'Nom d\'utilisateur',
    '@global-password': 'Mot de passe',
    '@global-submit': 'Envoyer',
    '@global-remain': 'Rester connecté',
    '@global-dashboard': 'Tableau de bord',
    '@global-dashboards': 'Tableaux de bord',
    '@global-dashboardslists': 'Listes de tableaux de bord',
    '@global-dashboardslist': 'Liste de tableaux de bord',
    '@global-reports': 'Rapports',
    '@global-trends': 'Tendances',
    '@global-trend': 'Tendance',
    '@global-points': 'Points',
    '@global-point': 'Point',
    '@global-folders': 'Dossiers',
    '@global-folder': 'Dossier',
    '@global-trendsgroups': 'Groupes de tendances',
    '@global-trendsgroup': 'Groupe de tendances',
    '@global-locations': 'Emplacements',
    '@global-location': 'Emplacement',
    '@global-sites': 'Sites',
    '@global-site': 'Site',
    '@global-breakers': 'Disjoncteurs',
    '@global-localization': 'Localisation',
    '@global-identifier': 'Identifiant',
    '@global-groups': 'Groupes',
    '@global-dataProviders': 'Fournisseurs de données',
    '@global-dataProvider': 'Fournisseur de données',
    '@global-internal': 'Interne',
    '@global-consumption': 'Consommation',
    '@global-consumptions': 'Consommations',
    '@global-energy': 'Energie',
    '@global-alarms': 'Alarmes',
    '@global-categories': 'Catégories',
    '@global-warnings': 'Attention',
    '@global-remembers': 'Notes',
    '@global-validations': 'Validations',
    '@global-profile': 'Profil',
    '@global-settings': 'Paramètres',
    '@global-contact': 'Contact',
    '@global-help': 'Aide',
    '@global-learn-more': 'En s\'avoir plus',
    '@global-type': 'Type',
    '@global-date': 'Date',
    '@global-position': 'Position',
    '@global-positions': 'Positions',
    '@global-no': 'Non',
    '@global-yes': 'Oui',
    '@global-connection': 'Connexion',
    '@global-message': 'Message',
    '@global-alarm-date': 'Date alarme',
    '@global-ack-date': 'Acquittée',
    '@global-drop-date': 'Date normal',
    '@global-measures': 'Mesures',
    '@global-value': 'Valeur',
    '@global-state': 'Etat',
    '@global-configuration': 'Configuration',
    '@global-commissioning': 'Mise en service',
    '@global-water': 'Eau',
    '@global-electricity': 'Electricité',
    '@global-temperature': 'Température',
    '@global-disjunction': 'Disjonction',
    '@global-zone-exit': 'Sortie de zone',
    '@global-total': 'Total',
    '@global-powered': 'Alimentée',
    '@global-not-powered': 'Non alimentée',
    '@global-battery-level': 'Niveau de batterie',
    '@global-unknow': 'Inconnu',
    '@global-online': 'En ligne',
    '@global-offline': 'Hors ligne',
    '@global-plug': 'Branché',
    '@global-unplug': 'Débranché',
    '@global-treeview': 'Vue arborescente',
    '@global-filter': 'Filtre',
    '@global-heatmap': 'Heatmap',
    '@global-general': 'Général',
    '@global-parent': 'Parent',
    '@global-reference': 'Référence',
    '@global-source': 'Source',
    '@global-singleTrend': 'Tendance simple',
    '@global-multipleTrends': 'Tendances multiples (plusieurs index)',
    '@global-manualEntry': 'Saisie manuelle',
    '@global-multipleManualEntries': 'Saisie manuelle (plusieurs index)',
    '@global-expression': 'Expression',
    '@global-conversion': 'Conversion',
    '@global-coefficient': 'Coefficient',
    '@global-offset': 'Décalage',
    '@global-other': 'Autre',
    '@global-unit': 'Unité',
    '@global-use': 'Usage',
    '@global-tariff': 'Tarif',
    '@global-tariffs': 'Tarifs',
    '@global-report': 'Rapport',
    '@global-group': 'Groupe',
    '@global-color': 'Couleur',
    '@global-default': 'Défaut',
    '@global-tolerance': 'Tolérance',
    '@global-condition': 'Condition',
    '@global-severity': 'Severité',
    '@global-thresholds': 'Seuils',
    '@global-threshold': 'Seuil',
    '@global-plannings': 'Plannings',
    '@global-planning': 'Planning',
    '@global-customProperties': 'Propriétés personnalisées',
    '@global-customProperty': 'Propriété personnalisée',
    '@global-server': 'Serveur',
    '@global-size': 'Taille',
    '@global-database': 'Base de données',
    '@global-udds': 'Degrés jours',
    '@global-none-m': 'Aucun',
    '@global-none-f': 'Aucune',
    '@global-calculated': 'Calculé',
    '@global-base': 'Base',
    '@global-method': 'Méthode',
    '@global-calendar': 'Calendrier',
    '@global-calendars': 'Calendriers',
    '@global-mediane': 'Médiane',
    '@global-average': 'Moyenne',
    '@global-simple': 'Simple',
    '@global-pro': 'Pro',
    '@global-search': 'Rechercher',
    '@global-elements': 'Eléments',
    '@global-personalized': 'Personnalisé',
    '@global-display': 'Affichage',
    '@global-display_verb': 'Afficher',
    '@global-activate': 'Activé',
    '@global-definition': 'Définition',
    '@global-refreshTime': 'Temps de rafraichissement',
    '@global-refreshPeriod': 'Période de rafraichissement',
    '@global-mode': 'Mode',
    '@global-tables': 'Tables',
    '@global-localTime': 'Temps local',
    '@global-utc': 'UTC',
    '@global-fileTime': 'FileTime',
    '@global-fileTimeDesc': '100 ns intervals since 1601/1/1',
    '@global-optional': 'Optionnel',
    '@global-connections': 'Connexions',
    '@global-configure': 'Configurer',
    '@global-integrated': 'Intégrée',
    '@global-enable': 'Activer',
    '@global-disable': 'Désactiver',
    '@global-disabled': 'Désactiver',
    '@global-customized': 'Personnalisé',
    '@global-none': 'Aucune',
    '@global-data:': 'Données',
    '@global-onChanges': 'Sur changement',
    '@global-title': 'Titre',
    '@global-defaultPeriod': 'Période par défaut',
    '@global-offsetUnit': '',
    '@global-secondOffset': 'Deuxième décalage',
    '@global-duration': 'Durée',
    '@global-durationUnit': '',
    '@global-background': 'Fond',
    '@global-foreground': 'Premier plan',
    '@global-image': 'Image',
    '@global-opacity': 'Opacité',
    '@global-browse': 'Rechercher',
    '@global-period': 'Période',
    '@global-picture': 'Image',
    '@global-functions': 'Fonctions',
    '@global-columns': 'Colonnes',
    '@global-rows': 'Rangée',
    '@global-actions': 'Actions',
    '@global-action': 'Action',
    '@global-width': 'Largeur',
    '@global-height': 'Hauteur',
    '@global-displayValue': 'Afficher la valeur',
    '@global-format': 'Format',
    '@global-minimum': 'Minimum',
    '@global-maximum': 'Maximum',
    '@global-level': 'Niveau',
    '@global-legend': 'Légende',
    '@global-perUnitOfArea': 'Par unité de surface',
    '@global-url': 'URL',
    '@global-fontSize': 'Taille de police',
    '@global-beginning': 'Début',
    '@global-primary': 'Energie primaire',
    '@global-carbon': 'Carbone',
    '@global-cost': 'Coût',
    '@global-unitPrice': 'Prix unitaire',
    '@global-textColor': 'Couleur du texte',
    '@global-backgroundImage': 'Image d\'arrière plan',
    '@global-hardwareAddress': 'Adresse physique',
    '@global-options': 'Options',
    '@global-status': 'Status',
    '@global-instance': 'Instance',
    '@global-ipAddress': 'Adresse Ip',
    '@global-port': 'Port',
    '@global-portUdp': 'Port UDP',
    '@global-standardPort': 'Port standard',
    '@global-range': 'Etendue',
    '@global-address': 'Adresse',
    '@global-addresses': 'Adresses',
    '@global-from': 'De',
    '@global-to': 'À',
    '@global-global': 'Global',
    '@global-local': 'Local',
    '@global-remote': 'Distant',
    '@global-broadcast': 'Broadcast',
    '@global-numberOfRetries': 'Nombre max. d\'essais',
    '@global-requestTimeout': 'Délais attente réponse',
    '@global-import': 'Importer',
    '@global-objCount': 'Nombre \'objets',
    '@global-vendorId': 'Vendor Id',
    '@global-addressLength': 'Longueur d\'adresse',
    '@global-pollingPeriod': 'Période de scrutation',
    '@global-clockSyncPeriod': 'Période de synchro des horloges',
    '@global-explorationDuration': 'Durée d\'exploration',
    '@global-unlimited': 'Illimité',
    '@global-maxTransactionsPerDevice': 'Transactions max. par appareil',
    '@global-multiple' : 'Sélection multiple',
    '@global-play': 'Lancer',
    '@global-energyEfficiencyRating': 'Indice de performance énergétique',
    '@global-indicator' : 'Indicateur',
    '@global-template': 'Modèle',
    '@global-templates': 'Modèles',
    '@global-startDate': 'Date de départ',
    '@global-endDate': 'Date de fin',
    '@global-defaultElement': 'Elément par défaut',
    '@global-orientation': 'Orientation',
    '@global-portrait': 'Portrait',
    '@global-landscape': 'Paysage',
    '@global-borderColor': 'Couleur de bordure',
    '@global-authorization': 'Autorisation',
    '@global-leftImage': 'Image gauche',
    '@global-rightImage': 'Image droite',
    '@global-logo': 'Logo',
    '@global-leftLogo': 'Logo gauche',
    '@global-rightLogo': 'Logo droite',
    '@global-content': 'Contenu',
    '@global-newLine': 'Nouvelle ligne',
    '@global-newPage': 'Nouvelle page',
    '@global-sampling': 'Echantillonnage',
    '@global-element': 'Elément',
    '@global-axis': 'Axes',
    '@global-text': 'Texte',
    '@global-pie': 'Graphe secteur',
    '@global-formatting': 'Mise en forme',
    '@global-infos': 'Infos',
    '@global-field': 'Champ',
    '@global-fields': 'Champs',
    '@global-variable': 'Variable',
    '@global-variables': 'Variables',
    '@global-attributes': 'Attributs',
    '@global-sum': 'Somme',
    '@global-parameters': 'Paramètres',
    '@global-dataToDisplay': 'Données à afficher',
    '@global-data': 'Données',
    '@global-showValue': 'Afficher la valeur',
    '@global-showValues': 'Afficher les valeurs',
    '@global-legends': 'Légendes',
    '@global-valueOfCurrentElement': 'Valeur de l\'élément courant',
    '@global-greenHouseGasEmission': 'Emission de gaz à effet de serre',
    '@global-exportInProgress': 'Export en cours',
    '@global-export': 'Exporter',
    '@global-exportHistory': 'Exporter l\'historique',
    '@global-exportGrid': 'Exporter le tableau',
    '@global-exportConfiguration': 'Exporter la configuration',
    '@global-separator': 'Séparateur',
    '@global-displayInfo': 'Afficher les informations',
    '@global-numberOfValues': 'Nombre de valeurs',
    '@global-lastValue': 'Dernière valeur',
    '@global-performance': 'Performance',
    '@global-network': 'Réseau',
    '@global-trace': 'Trace',
    '@global-connectionType': 'Type de connection',
    '@global-serialPort': 'Port série',
    '@global-baudRate': 'Vitesse',
    '@global-timeout': 'Timeout',
    '@global-errors': 'Erreures',
    '@global-statistics': 'Statistiques',
    '@global-registers': 'Registres',
    '@global-connecting': 'Connexion',
    '@global-connected': 'Connecté',
    '@global-disconnected': 'Déconnecté',
    '@global-lastError': 'Dernière erreur',
    '@global-numberOfTries': 'Nombre d\'essais',
    '@global-cycleDuration': 'Durée cycle',
    '@global-lowByteFirst': 'Octet de poids faible en premier',
    '@global-lowWordFirst': 'Mot de poids faible en premier',
    '@global-count': 'Nombre',
    '@global-copiedToClipboard': 'Copié dans le presse-papier',
    '@global-copyUrl': 'Copier l\'url',
    '@global-distribution': 'Répartition',
    '@global-files': 'Fichiers',
    '@global-file': 'Fichier',
    '@global-path': 'Chemin',
    '@global-drive': 'Disque',
    '@global-and': 'et',
    '@global-active': 'Actif',
    '@global-passive': 'Passif',
    '@global-preview': 'Aperçu',
    '@global-clearCache': 'Effacer le cache',
    '@global-list': 'Liste',
    '@global-editionMode': 'Mode édition',
    '@global-fullscreen': 'Plein écran',
    '@global-start_verb': 'Démarrer',
    '@global-noMenu': 'Aucun menu',
    '@global-left': 'Gauche',
    '@global-right': 'Droite',
    '@global-min': 'Min',
    '@global-max': 'Max',
    '@global-baseline': 'Référence',
    '@global-displayIndex': 'Afficher l\'index',
    '@global-showIndicator': 'Afficher l\'indicateur',
    '@global-fontColor': 'Couleur du texte',
    '@global-tiles': 'Tuiles',
    '@global-deleteFromList': 'Supprimer de la liste',
    '@global-nullAsZero': 'Remplacer une valeur absente par zéro',
    '@global-dynamicColors': 'Couleurs dynamiques',
    '@global-defaultFontColor': 'Couleur du texte par défaut',
    '@global-defaultTextColor': 'Couleur du texte par défaut',
    '@global-defaultBackground': 'Couleur de l\'arrière plan par défaut',
    '@global-defaultTitleColor': 'Couleur du titre par défaut',
    '@global-titleColor': 'Couleur du titre',
    '@global-consump./product.': 'Consump./Product.',
    '@global-production': 'Production',
    '@global-instances': 'Instances',
    '@global-comments': 'Commentaires',
    '@global-comment': 'Commentaire',
    '@global-miscellaneous': 'Divers',
    '@global-misc.': 'Divers',
    '@global-minDuration': 'Durée minimum',
    '@global-dates': 'Dates',
    '@global-affectation-date': 'Date d\'affectation',
    '@global-last-communication-date': 'Dernière communication',
    '@global-startdate': 'Date de début',
    '@global-enddate': 'Date de fin',
    '@global-decennary': 'Décennie',
    '@global-year': 'Année',
    '@global-month': 'Mois',
    '@global-week': 'Semaine',
    '@global-day': 'Jour',
    '@global-hour': 'Heure',
    '@global-minute': 'Minute',
    '@global-seconde': 'Seconde',
    '@global-per-year': 'Par Année',
    '@global-per-month': 'Par Mois',
    '@global-per-week': 'Par Semaine',
    '@global-per-day': 'Par Jour',
    '@global-per-hour': 'Par Heure',
    '@global-per-minute': 'Par Minute',
    '@global-per-seconde': 'Par Seconde',
    '@global-daily': 'Journalière',
    '@global-monthly': 'Mensuelle',
    '@global-yearly': 'Annuelle',
    '@global-currentHour': 'Heure courante',
    '@global-currentDay': 'Jour courant',
    '@global-currentWeek': 'Semaine courante',
    '@global-currentMonth': 'Mois courant',
    '@global-currentYear': 'Année courante',
    '@global-hours': 'Heures',
    '@global-days': 'Jours',
    '@global-weeks': 'Semaines',
    '@global-months': 'Mois',
    '@global-years': 'Années',
    '@global-seconds': 'Secondes',
    '@global-currentDate': 'Date courrante',
    '@global-nameOfMonth': 'Nom du mois',
    '@global-weekNumber': 'Numéro de la semaine',
    '@global-january': 'Janvier',
    '@global-february': 'Février',
    '@global-march': 'Mars',
    '@global-april': 'Avril',
    '@global-may': 'Mai',
    '@global-june': 'Juin',
    '@global-july': 'Juillet',
    '@global-august': 'Août',
    '@global-september': 'Septembre',
    '@global-october': 'Octobre',
    '@global-november': 'Novembre',
    '@global-december': 'Décembre',
    '@global-january_abrv': 'Jan',
    '@global-february_abrv': 'Fev',
    '@global-march_abrv': 'Mar',
    '@global-april_abrv': 'Avr',
    '@global-may_abrv': 'Mai',
    '@global-june_abrv': 'Juin',
    '@global-july_abrv': 'Juil',
    '@global-august_abrv': 'Aoû',
    '@global-september_abrv': 'Sep',
    '@global-october_abrv': 'Oct',
    '@global-november_abrv': 'Nov',
    '@global-december_abrv': 'Déc',
    '@global-monday': 'Lundi',
    '@global-tuesday': 'Mardi',
    '@global-wednesday': 'Mercredi',
    '@global-thursday': 'Jeudi',
    '@global-friday': 'Vendredi',
    '@global-saturday': 'Samedi',
    '@global-sunday': 'Dimanche',
    '@global-monday_abrv': 'Lun.',
    '@global-tuesday_abrv': 'Mar.',
    '@global-wednesday_abrv': 'Mer.',
    '@global-thursday_abrv': 'Jeu.',
    '@global-friday_abrv': 'Ven.',
    '@global-saturday_abrv': 'Sam.',
    '@global-sunday_abrv': 'Dim.',
    '@global-previousDay': 'Jour précédent',
    '@global-previousWeek': 'Semaine précédente',
    '@global-previousMonth': 'Mois précédent',
    '@global-previousYear': 'Année précédente',
    '@global-alarm': 'Alarme',
    '@global-lessThan': 'Moin que',
    '@global-greaterThan': 'Plus grand que',
    '@global-referenceYear': 'Année de référence',
    '@global-manualEntries': 'Saisies manuelles',
    '@global-addValue': 'Ajouter une valeur',
    '@global-deleteValue': 'Supprimer une valeur',
    '@global-accumulation': 'Accumulation',
    '@global-difference': 'Différence',
    '@global-price': 'Prix',
    '@global-newReading': 'Nouveau relevé',
    '@global-plans': 'Plans',
    '@global-plan': 'Plan',
    '@global-saveAndExit': 'Sauvegarder et quitter',
    '@global-exitWithoutSave': 'Quitter sans sauvegarder',
    '@global-borderSize': 'Border size',
    '@global-edition': 'Edition',
    '@global-save': 'Sauvegarder',
    '@global-exit': 'Quitter',
    '@global-phase': 'Phase',
    '@global-input': 'Entrée',
    '@global-output': 'Sortie',
    '@global-ups': 'Onduleur',
    '@global-rack': 'Baie',
    '@global-crac': 'Climatisation',
    '@global-apparentPower': 'Puissance apparente',
    '@global-activePower': 'Puissance active',
    '@global-reactivePower': 'Puissance réactive',
    '@global-powerFactor': 'Facteur de puissance',
    '@global-current': 'Courant',
    '@global-voltage': 'Tension',
    '@global-batteryCharge': 'Charge batterie',
    '@global-frequency': 'Fréquence',
    '@global-reactiveEnergy': 'Energie réactive',
    '@global-temperatureIn': 'Température entrée',
    '@global-temperatureOut': 'Température sortie',
    '@global-load': 'Charge',
    '@global-outletState': 'Etats des prises',
    '@global-sort': 'Tri',
    '@global-sorting': 'Trier',
    '@global-criterion': 'Critère',
    '@global-criteria': 'Critères',
    '@global-attribute': 'Attribut',
    '@global-maxCount': 'Nombre maximum',
    '@global-sortDirection': 'Sens de tri',
    '@global-ascending': 'Ascendant',
    '@global-descending': 'Descendant',
    '@global-function': 'Fonction',
    '@global-convertion': 'Convertion',
    '@global-ratio': 'Ratio',
    '@global-finalEnergy': 'Energie finale',
    '@global-primaryEnergy': 'Energie primaire',
    '@global-cO2': 'CO²',
    '@global-indexStart': 'Index de départ',
    '@global-indexStop': 'Index de fin',
    '@global-perAreaUnit': 'Par unité de surface',
    '@global-perDegreeDays': 'Par degré jours',
    '@global-first': 'Premier',
    '@global-last': 'Dernier',
    '@global-rename': 'Renommer',
    '@global-research': 'Rechercher',
    '@global-showCrosshair': 'Afficher le réticule',
    '@global-trendPeriod': 'Période tendance',
    '@global-communityRead': 'Communauté lecture',
    '@global-communityWrite': 'Communauté écriture',
    '@global-hostname': 'Nom d\'hôte',
    '@global-version': 'Version',
    '@global-supportMultipleRequests': 'Support multiple requests',
    '@global-explore': 'Explorer',
    '@global-pdus': 'PDUs',
    '@global-upss': 'Onduleurs',
    '@global-cracs': 'Climatisations',
    '@global-racks': 'Baies',
    '@global-compartments': 'Compartiments',
    '@global-maxAmp': 'Amp. max',
    '@global-power': 'Puissance',
    '@global-amp': 'Ampérage',
    '@global-tempIn': 'Temp. in',
    '@global-tempOut': 'Temp. out',
    '@global-maxCurrent': 'Courant max',
    '@global-appPower': 'Puissance app.',
    '@global-actPower': 'Puissance act.',
    '@global-reactPower': 'Puissance réact.',
    '@global-temp': 'Temp.',
    '@global-maxVa': 'Max VA',
    '@global-battery': 'Batterie',
    '@global-inputVoltage': 'Tension d\'entrée',
    '@global-pf': 'Cosφ',
    '@global-displayRealTimeState': 'Afficher l\'état en temps réel',
    '@global-fixed': 'Fixe',
    '@global-activity': 'Activité',
    '@global-heating': 'Chauffage',
    '@global-cooling': 'Climatisation',
    '@global-heatingReference': 'Chauffage de référence',
    '@global-coolingReference': 'Climatisation de référence',
    '@global-region': 'Région',
    '@global-building': 'Bâtiment',
    '@global-datacenter': 'Datacenter',
    '@global-corridor': 'Allée',
    '@global-row': 'Rangée',
    '@global-latitude': 'Latitude',
    '@global-longitude': 'Longitude',
    '@global-axes': 'Axes',
    '@global-print': 'Impression',
    '@global-print_verb': 'Imprimer',
    '@global-cumul': 'Cumul',
    '@global-normalized': 'Normalisé',
    '@global-byDegreeDays': 'Par degré jours',
    '@global-showPreviousYear': 'Afficher l\'année précédente',
    '@global-cumulated': 'Cumulé',
    '@global-power/flowRate': 'Puissance/Débit',
    '@global-informations': 'Informations',
    '@global-clientOperatingSystem': 'Système d\'exploitation client',
    '@global-environmentCode': 'Code d\'environnement',
    '@global-licenseState': 'Etat de la licence',
    '@global-organizations': 'Organisations',
    '@global-remoteSyncEnabled': 'Remote sync. enabled',
    '@global-remoteSyncServerEnabled': 'Remote sync. server enabled',
    '@global-license': 'Licence',
    '@global-sentMessage': 'Message envoyé',
    '@global-sendMessage': 'Envoyer un message',
    '@global-media': 'Media',
    '@global-recipient': 'Destinataire',
    '@global-recipients': 'Destinataires',
    '@global-normal': 'Normal',
    '@global-acked': 'Acquittée',
    '@global-subject': 'Sujet',
    '@global-groupMessages': 'Grouper les messages',
    '@global-notactivated': 'Non activée',
    '@global-every': 'Toutes les',
    '@global-created': 'Created',
    '@global-updated': 'Updated',
    '@global-deleted': 'Deleted',
    '@default-data': 'Données par défaut',
    '@default-period': 'Period par défaut',
    '@default-element': 'Elément par défaut',
    '@default-elements': 'Eléments par défaut',
    '@default-parameters': 'Paramètres par défaut',
    '@default-list': 'Liste par défaut',
    '@default-duration': 'Durée par défaut',
    '@period-refresh': 'Période de rafraîchissement',
    '@period-equivalent': 'Période équivalente',
    '@period-equivalentToCurrent': 'Période équivalente à la période actuelle',
    '@period-waitEnd': 'Attendre la fin de la période',
    '@start-none': 'Aucun',
    '@offset-none': 'Aucun',
    '@element-none': 'Aucun',
    '@element-add': 'Ajouter un élément',
    '@elements-import': 'Importer des éléments',
    '@tariff-simple': 'Tarif simple',
    '@tariff-multipleStats': 'Tarif multi-états',
    '@tariff-adjustment': 'Ajustement de tariff',
    '@meter-id': 'Id',
    '@meter-name': 'Nom',
    '@meter-locationId': 'Id de l\'emplacement',
    '@meter-consumption': 'Consommation',
    '@meter-nature': 'Nature',
    '@meter-unit': 'Unité',
    '@meter-location': 'Emplacement',
    '@meter-area': 'Surface',
    '@meter-expression': 'Expression',
    '@meter-organization': 'Organization',
    '@meter-indexlastvalue' : 'Dernier index',
    '@meter-indexlastdate' : 'Date de la dernière valeur',
    '@meter-nometerfound': 'Aucun compteur trouvé',
    '@meter-principal': 'Compteur principal',
    '@meter-accumulation': 'Accumulation',
    '@meter-noInterpolation': 'Sans interpolation',
    '@meter-scalingCoef': 'Coef. mise à l\'échelle',
    '@meter-distributionCoef': 'Coef. de distribution',
    '@meter-rolloverLimit': 'Valeur de débordement',
    '@meter-maxDaily': 'Conso jour max (0 = auto)',
    '@meter-onlyUsed': 'Seulement les compteurs utilisés',
    '@meter-create' : 'Créer un compteur',
    '@meter-list' : 'Liste des compteurs',
    '@meter-addSub': 'Ajouter un sous compteur',
    '@meter-none': 'Aucun compteur',
    '@meter-shift': 'Recaler le compteur',
    '@meter-newShift': 'Nouveau recalage',
    '@meters-(automatic)': 'Compteurs (automatique)',
    '@meters-(manual)': 'Compteurs (manuel)',
    '@meters-(other)': 'Compteurs (autre)',
    '@meter-noManualEntryAvailable': 'Aucun compteur en mode entrée manuelle disponible',
    '@location-type': 'Type d\'emplacement',
    '@location-includeSub': 'Inclure les sous-emplacements',
    '@location-addSub': 'Ajouter un sous emplacement',
    '@location-none': 'Aucun emplacement',
    '@location-moveTo': 'Déplacer vers un emplacement',
    '@location-addMeterTo': 'Ajouter un compteur à l\'emplacement',
    '@location-deleteFrom': 'Supprimer de l\'emplacement',
    '@location-by': 'Par emplacement',
    '@group-includeSub': 'Inclure les sous-groupes',
    '@group-addSub': 'Ajouter un sous groupe',
    '@group-none': 'Aucun group',
    '@group-basedOnSubGroups': 'basée sur les sous-groupes',
    '@group-basedOnMeters': 'basée sur les compteurs',
    '@group-addTo': 'Ajouter à un groupe',
    '@group-addMeterTo': 'Ajouter un compteur au groupe',
    '@group-deleteFrom': 'Supprimer du groupe',
    '@object-type': 'Type d\'objet',
    '@alarm-only-active': 'Seulement les alarmes en cours',
    '@alarm-only-active-or-unacked': 'Seulement les alarmes actives ou non-acquittées',
    '@alarm-instances': 'Instances d\'alarme',
    '@alarm-configuration': 'Configuration des alarmes',
    '@alarm-history': 'Historique d\'alarme',
    '@alarms-definitions': 'Définitions d\'alarmes',
    '@alarm-ack': 'Acquitter l\'alarme',
    '@alarm-active': 'Alarme active',
    '@alarm-deactive': 'Alarme inactive',
    '@alarm-ackActive': 'Alarme acquittée et active',
    '@alarm-ackDeactive': 'Alarme acquittée et inactive',
    '@alarm-none': 'Aucune',
    '@alarm-presents': 'Alarmes actuelles',
    '@alarm-defaultMessage': 'Message d\'alarme par défaut',
    '@alarm-personalizedMessage': 'Message d\'alarme personnalisé',
    '@alarm-state': 'Etat de l\'alarme',
    '@alarm-date': 'Date de l\'alarme',
    '@alarm-message': 'Message de l\'alarme',
    '@alarm-identifier': 'Identifiant de l\'alarme',
    '@alarm-category': 'Catégorie de l\'alarme',
    '@alarm-nameOfAssocatedElement': 'Nom de l\'élément associé (point, tendance, ...)',
    '@alarm-valueOfAssocatedElement': 'Valeur de l\'élément associé (point, tendance, ...)',
    '@alarm-stateOfAssocatedPlanning': 'Etat du planning associé à l\'alarme',
    '@alarm-location': 'Emplacement de l\'alarme',
    '@alarm-describtionOfLocation': 'Déscription de l\'emplacement de l\'alarme',
    '@alarm-locationOfLocation': 'Emplacement parent de l\'emplacement de l\'alarme',
    '@alarm-labelOfpropertyOfAssocatedDevice': 'Libellé de la propriété de l\'appareil associé',
    '@alarm-lebalOfAssocatedMeasure': 'Libellé de la mesure associé',
    '@site-history': 'Historique des chantiers',
    '@site-add': 'Ajouter un chantier',
    '@site-edit-zone': 'Editer la zone du chantier',
    '@connection-add': 'Ajouter une connexion',
    '@connection-edit': 'Editer la connexion',
    '@connection-delete': 'Supprimer la connexion',
    '@connection-refresh': 'Rafraîchir connexion',
    '@connection-update': 'Mettre à jour la connexion',
    '@connection-tcp': 'Connexion Tcp',
    '@connection-test': 'Test de la connexion',
    '@connection-serial': 'Connexion série',
    '@connection-success': 'Connexion réussie',
    '@connection-failed': 'Connexion échouée',
    '@consumption-degrees_day' : 'Degré-Jours',
    '@consumption-electricity-of' : 'Consommation d\'éléctricité',
    '@consumption-water-of' : 'Consommation d\'eau',
    '@consumption-reference': 'Consommation de référence',
    '@consumption-baseline': 'Consommation de référence',
    '@source-none': 'Aucune',
    '@alarm-definition': 'Définition d\'alarme',
    '@device-type': 'Type d\'appareil',
    '@device-data-provider': 'Fournisseur de données',
    '@device-reference': 'Référence',
    '@device-geolocation': 'Géolocalisation',
    '@device-all': 'Tous les appareils',
    '@device-add': 'Ajouter un appareil',
    '@device-edit': 'Editer l\'appareil',
    '@device-update': 'Mettre à jour l\'appareil',
    '@device-delete': 'Supprimer l\'appareil',
    '@device-explore': 'Explorer l\'appareil',
    '@device-instance': 'Instance de l\'appareil',
    '@device-statusPeriod': 'Période état appareil',
    '@devices-import': 'Importation d\'appareils',
    '@devices-display': 'Afficher les appareils',
    '@cabinet-add': 'Ajouter une armoire',
    '@cabinet-validate-position': 'Valider la position de l\'armoire',
    '@cabinet-edit-position': 'Editer la position de l\'armoire',
    '@cabinet-delete-position': 'Supprimer la position de l\'armoire',
    '@cabinets-by-type': 'Trier par type d\'armoire',
    '@trend-none': 'Aucune',
    '@trend-all': 'Toutes les tendances',
    '@trend-udds': 'Tendance degrés-jours',
    '@trend-outdoorTemperature': 'Tendance température extérieure',
    '@trend-create': 'Créer une tendance',
    '@trend-fromPoint': 'Tendance à partir d\'un point',
    '@trend-conversion': 'Conversion tendance',
    '@trends-create': 'Créer des tendances',
    '@measure-temperature': 'Température',
    '@measure-battery': 'Batterie',
    '@unit-conversion': 'Conversion d\'unité',
    '@nature-electricity': 'Electricité',
    '@nature-water': 'Eau',
    '@nature-sourceEnergyCoef': 'Coef. Energie Primaire',
    '@nature-CO2PerUnit': 'Kg CO2 par unité',
    '@nature-by': 'Par nature',
    '@use-heating': 'Chauffage',
    '@use-cooling': 'Climatisation',
    '@dashboard-columnsNumber' : 'Nombre de colonnes',
    '@dashboard-rowsNumber' : 'Nombre de rangées',
    '@dashboard-tilesStyle' : 'Style des tuiles',
    '@dashboard-addTile' : 'Ajouter une tuile',
    '@dashboard-value' : 'Valeur',
    '@dashboard-chart' : 'Graphe barre / courbe',
    '@dashboard-pie' : 'Graphe secteur',
    '@dashboard-gauge' : 'Jauge',
    '@dashboard-indicator' : 'Indice de performance énergétique',
    '@dashboard-image' : 'Image',
    '@dashboard-autoUnit' : 'Unité automatique',
    '@dashboard-textColor' : 'Couleur texte',
    '@dashboard-dynamicColors' : 'Couleur de fond dynamique',
    '@dashboard-actionType' : 'Type d\'action',
    '@dashboard-bySubLocationGroup' : 'Par sous-emplacement/groupe',
    '@dashboard-byNature' : 'Par nature',
    '@dashboard-showPercentage' : 'Afficher les pourcentages',
    '@dashboard-showValue' : 'Afficher les valeurs',
    '@dashboard-deleteFromList': 'Supprimer de la liste',
    '@dashboard-showTrend': 'Afficher une tendance',
    '@dashboard-showTrendsGroup': 'Afficher un groupe de tendances',
    '@dashboard-openWebPage': 'Ouvrir une page web',
    '@dashboard-showDashboard': 'Afficher un tableau de bord',
    '@dashboard-showConsumptionHistory': 'Afficher un historique de consommation',
    '@dashboard-meterListDesc': '',
    '@dashboard-lists': 'Listes des tableaux de bord',
    '@dashboard-list': 'Liste des tableaux de bord',
    '@dashboard-all': 'Tous les tableaux de bord',
    '@dashboard-options': 'Options des tableaux de bord',
    '@dashboard-tileDefaultColor': 'Changer la couleur de la tuile (si la valeur est indisponible)',
    '@point-all': 'Tous les points',
    '@point-readValue': 'Lire la valeur',
    '@point-readValues': 'Lire les valeurs',
    '@points-show': 'Afficher les points',
    '@report-all': 'Tous les rapports',
    '@report-none': 'Aucun',
    '@plan-all': 'Tous les plans',
    '@plan-properties': 'Propriétés du plan',
    '@udds-none': 'Aucun',
    '@udds-heating': 'Degrés jours chauffage',
    '@udds-cooling': 'Degrés jours climatisation',
    '@sampling-none': 'Aucun',
    '@method-none': 'Acune méthode',
    '@temperature-mediane': 'Utiliser la température médiane',
    '@temperature-average': 'Utiliser la température moyenne',
    '@temperature-input': 'Température d\'entrée',
    '@temperature-output': 'Température de sortie',
    '@temperature-indoor': 'Température intérieure',
    '@temperature-outdoor': 'Température extérieure',
    '@password-change': 'Changement de mot de passe',
    '@password-comfirmation': 'Le mot de passe de confirmation n\'est pas valide',
    '@password-change-success': 'Votre mot de passe a été changé avec succès',
    '@password-change-failed': 'Le changement de mot de passe a échoué',
    '@password-current': 'Mot de passe courant',
    '@password-new': 'Nouveau mot de passe',
    '@password-confirmation': 'Confirmation du mot de passe',
    '@password-cannot-change': 'Vous ne pouvez pas changer de mot de passe',
    '@configuration-save': 'Sauvegarder la configuration',
    '@database-infos': 'Informations sur la base de donées',
    '@database-connectionString': 'Chaîne de connexion',
    '@database-columns': 'Colonnes',
    '@database-columnsDate': 'Colonne de date',
    '@database-columnsValue': 'Colonne de valeur',
    '@database-columnsReference': 'Colonne de référence',
    '@database-mapping': 'Mapping',
    '@database-mappingListRef': 'Liste des noms / références',
    '@database-mappingRefConvert': 'Convertit un nom ({0}) en une référence utilisé dans la table des valeurs',
    '@database-sqlRequests': 'Requêtes SQL',
    '@database-name': 'Nom de la base de données',
    '@database-dbfFile': 'Fichier .Dbf',
    '@server-name': 'Nom du serveur',
    '@server-version': 'Version du serveur',
    '@server-add': 'Ajouter un serveur',
    '@server-memoryUsage(MB)': 'Utilisation de la mémoire du serveur (Mo)',
    '@zoom-reset': 'Réinit. zoom',
    '@xml-edit': 'Editer XML',
    '@xml-editor': 'Edition XML',
    '@entry': 'Saisie',
    '@entries': 'Saisies',
    '@entry-add': 'Ajouter une saisie',
    '@date-chooseA': 'Choisir une date',
    '@authentication-basic': 'Authentification basique',
    '@bacnet-configuration': 'Configuration BACnet',
    '@bacnet-exploration': 'Exploration BACnet',
    '@bacnet-networkNumber': 'Numéro de réseau BACnet',
    '@bacnet-impossibleImportTrendsAndPoints': 'Impossible d\'importer des points et des tendances simultanément',
    '@modbus-tcpHeader': 'Entête Modbus TCP',
    '@modbus-connectionConfiguration': 'Configuration connexion Modbus',
    '@modbus-deviceConfiguration': 'Configuration appareil Modbus',
    '@modbus-type_B': 'Binaire',
    '@modbus-type_Bi': 'Binaire (entrée)',
    '@modbus-type_D': 'Réel 64bits',
    '@modbus-type_Di': 'Réel 64bits (entrée)',
    '@modbus-type_F': 'Réel 32bits',
    '@modbus-type_Fi': 'Réel 32bits (entrée)',
    '@modbus-type_K': 'Entier 48bits',
    '@modbus-type_Ki': 'Entier 48bits (entrée)',
    '@modbus-type_Kis': 'Entier signé 48bits (entrée)',
    '@modbus-type_Ks': 'Entier signé 48bits',
    '@modbus-type_L': 'Entier 32bits',
    '@modbus-type_Li': 'Entier 32bits (entrée)',
    '@modbus-type_Lis': 'Entier signé 32bits (entrée)',
    '@modbus-type_LL': 'Entier 64bits',
    '@modbus-type_LLi': 'Entier 64bits (entrée)',
    '@modbus-type_LLis': 'Entier signé 64bits (entrée)',
    '@modbus-type_LLs': 'Entier signé 64bits',
    '@modbus-type_Ls': 'Entier signé 32bits',
    '@modbus-type_T': 'Texte',
    '@modbus-type_W': 'Entier 16bits',
    '@modbus-type_Wi': 'Entier 16bits (entrée)',
    '@modbus-type_Wis': 'Entier signé 16bits (entrée)',
    '@modbus-type_Ws': 'Entier signé 16bits',
    '@multitech-deletionAuthorization': 'Suppression d\'appareil autorisée',
    '@multitech-messages': 'Messages',
    '@multitech-lastmessage': 'Dernière date',
    '@multitech-nodeaddr': 'Node address',
    '@multitech-deveui': 'DevEui',
    '@multitech-rssi': 'Rssi',
    '@multitech-snr': 'Snr',
    '@multitech-datarate': 'Data rate',
    '@multitech-addr': 'Adr',
    '@multitech-appeui': 'AppEui',
    '@multitech-appkey': 'AppKey',
    '@multitech-class': 'Classe',
    '@multitech-otaa': 'OTAA',
    '@multitech-abp': 'ABP',
    '@multitech-periodicRetrievalOfMessages': 'Récupération périodique des messages',
    '@multitech-pollingPeriod': 'Période (secondes)',
    '@multitech-nodeRedConnectionEnabled': 'Connexion Node-RED activée',
    '@multitech-messageOnConnection': 'Récupération des messages à la connexion',
    '@multitech-statusCheck': 'Vérification de l\'état de la passerelle',
    '@file-types': 'Types de fichiers',
    '@file-import': 'Importer un fichier',
    '@file-paths': 'Chemin des fichiers',
    '@file-hasHeader': 'Le fichier a un entête',
    '@file-reading': 'Lecture du fichier',
    '@file-chooseRemote': 'Choisir un fichier distant',
    '@file-chooseLocal': 'Choisir un fichier local',
    '@file-choose': 'Choisir un fichier',
    '@file-name': 'Nom de fichier',
    '@network-number': 'Network number',
    '@network-explore': 'Explorer le réseau',
    '@network-interfaces': 'Interfaces réseau',
    '@consumption-history' : 'Historique de consommation',
    '@consumption-table': 'Tableau de consommation',
    '@consumption-chart': 'Graphe de consommation',
    '@consumption-graph': 'Graphe de consommation',
    '@consumption-conversion': 'Conversion consommation',
    '@consumption-useReference': 'Utiliser la consommation de référence',
    '@consumptions-normalized': 'Normaliser les consommations',
    '@tile-Titles': 'Titre des tuiles',
    '@chart-cumul': 'Graph cumulé',
    '@error-name-field-required': 'Le \'Nom\' est requis',
    '@error-this-field-required': 'Ce champ est requis',
    '@error-impossibleImportTrendsAndPoints': 'Impossible d\'importer des tendances et des points simultanément',
    '@sentence-consult-admin': 'Veuillez contacter votre administrateur réseau',
    '@sentence-no-data': 'Aucune données trouvées',
    '@sentence-are-you-sure': 'Êtes-vous sûr ?',
    '@sentence-server-connect': 'Impossible d\'établir une connexion avec le serveur',
    '@sentence-user-or-pass': 'Utilisateur ou mot de passe incorrect',
    '@sentence-remove-failed': 'La suppression a échoué',
    '@sentence-impossible-uo': 'Impossible de supprimer l\'UO tant qu\'il contient des chantiers',
    '@sentence-impossible-site': 'Impossible de supprimer le chantier tant qu\'il contient des armoires',
    '@sentence-unknown-url': 'URL inconnue',
    '@sentence-someValuesAreNotValidated.': 'Certaines valeurs ne sont pas validées',
    '@sentence-someValuesAreNotValidated.AreYouSureToContinue?': 'Certaines valeurs ne sont pas validées. Êtes-vous certain de vouloir continuer ?',
    '@info-warningIE': 'L\'application est optimisée pour les navigateurs modernes. Sur Internet Explorer l\'affichage risque d\'être dégradé',
    '@threshold-none': 'Aucun',
    '@type-none': 'Aucun',
    '@attribute-none': 'Aucun',
    '@filter-none': 'Aucun',
    '@filter-EqOperator': 'Est égal à',
    '@filter-NotEqOperator': 'N’est pas égal à',
    '@filter-IsNullOperator': 'Est nulle',
    '@filter-IsNotNullOperator': 'N’est pas nulle',
    '@filter-IsEmptyOperator': 'Est vide',
    '@filter-IsNotEmptyOperator': 'N’est pas vide',
    '@filter-StartsWithOperator': 'Commence par',
    '@filter-ContainsOperator': 'Contient',
    '@filter-NotContainsOperator': 'Ne contient pas',
    '@filter-EndsWithOperator': 'Se termine par',
    '@filter-GteOperator': 'Est supérieur ou égal à',
    '@filter-GtOperator': 'Est supérieur à',
    '@filter-LteOperator': 'Est inférieur ou égal à',
    '@filter-LtOperator': 'Est inférieur',
    '@filter-IsTrue': 'est vrai',
    '@filter-IsFalse': 'est fausse',
    '@filter-BooleanAll': '(Tout)',
    '@filter-AfterOrEqualOperator': 'Est postérieur ou égal à',
    '@filter-AfterOperator': 'Est postérieur',
    '@filter-BeforeOperator': 'Est antérieur',
    '@filter-BeforeOrEqualOperator': 'Est antérieur ou égal à',
    '@filter-FilterButton': 'Filtrer',
    '@filter-ClearButton': 'Effacer filtre',
    '@filter-AndLogic': 'Et',
    '@filter-OrLogic': 'Ou',
};
